# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [5]:
array=np.zeros(10)
print("array")
print(array)

array
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [6]:
array=np.ones(10)
print("array")
print(array)

array
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [10]:
array=np.ones(10)*5
print("array")
print(array)

array
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [12]:
array=np.arange(10,51)
print("array")
print(array)

array
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [13]:
array=np.arange(10,51,2)
print("array")
print(array)

array
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [15]:
array_2D = np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [36]:
randomnum = np.random.rand(1,1)
print(randomnum)

[[0.63993854]]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [20]:
randomnum = np.random.normal(0,1,25)
print(randomnum)

[ 0.17652734 -0.19622483  1.00238884 -0.34751595  2.43653671  0.8282303
  0.25442941  0.41502973 -0.33223016  1.67979528 -0.48209655 -1.10097932
 -1.01228389 -0.52766779 -0.30534739 -0.0912678  -1.07694297  1.40536399
  0.04183114  1.36802525  0.50092312  0.76063804 -1.77691152 -0.66718378
 -1.28783652]


#### Create the following matrix:

In [22]:
randomnum = np.random.normal(0,1,100).reshape(20,5)
print(randomnum)

[[-0.67965194  2.16233221  1.5263965   0.29847753 -1.78023898]
 [-0.27571809 -0.00637617 -0.80509427 -1.68043783 -0.34109119]
 [ 0.3445362  -0.00944072  0.8248816   2.37670202 -0.95424273]
 [-0.68590472  0.47674112 -0.40572171 -0.16904535  0.31060904]
 [-0.67757084  1.06876529 -0.25865074  0.05562039  2.51580387]
 [-2.31244773 -1.60913277  1.88022272  0.78136409  0.85724771]
 [ 0.37985236  1.54128503 -1.2891349  -2.87363212  0.4928285 ]
 [-0.46063972 -0.09479347  0.05047     0.1508078  -0.8263573 ]
 [ 0.74629667  1.36457531 -1.22297912 -0.58664828  1.80882774]
 [ 0.69189812  0.97756976  0.2328426  -0.2245513   1.83988914]
 [ 0.81672916 -0.89040267 -0.76564712  0.33907016 -1.29750681]
 [ 0.85135235 -0.35816784  0.90827367 -1.90370381  1.91171786]
 [-1.91173561 -0.58850331  1.05592168  0.96551635 -0.96000265]
 [-1.80588483 -0.82838484 -1.08861112  0.2837831  -0.37369125]
 [ 0.35469519 -0.64049319  0.14764349  0.33017322  0.04037164]
 [ 0.47424204 -0.43224908  1.94233995 -0.37448117  2.42

#### Create an array of 20 linearly spaced points between 0 and 1:

In [23]:
randomnum = np.random.normal(0,1,0.052).reshape(4,5)
print(randomnum)

TypeError: 'float' object cannot be interpreted as an integer

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [37]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [38]:
matrix[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [39]:
matrix[3,4]

20

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [27]:
x =  np.arange(2,13,5).reshape(3,1)
print(x)

[[ 2]
 [ 7]
 [12]]


In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [31]:
x =  np.arange(21,26).reshape(1,5)
print(x)

[[21 22 23 24 25]]


In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [32]:
x =  np.arange(16,26).reshape(2,5)
print(x)

[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [40]:
print(matrix.sum())

325


#### Get the standard deviation of the values in mat

In [41]:
print(matrix.std())

7.211102550927978


#### Get the sum of all the columns in mat

In [42]:
print(matrix.sum(axis=1))

[ 15  40  65  90 115]


# Great Job!